### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by UMP-45** [Chen-Si-An/MeshReconstruction#1]
Thanks for this amazing work，I build it successfully, but I can‘t run “.exe”， it shows that “0x000007b” error, how to fix it? ; and why it need mfcs140u.lib?

**Comment by Chen-Si-An** [comment]
Can you provide more details about the issue you encountered? After reviewing the code, I couldn't identify the reason why this program requires mfcs140u.lib. I also ran the program in Visual Studio and observed that it doesn't link this particular DLL as expected.

**Comment by UMP-45** [comment]
Thanks for your reply. I use vs2019(v142),  cuda 11.3, pcl 1.13.1.After I changed the way I read .ply file by using vcg io module to get rid of mfcs140u.lib, the program ran successfully.But it's not as fast as I thought.A point cloud with 200,000 points, average point distance is 0.19mm, I use 0.2 as ball radius, this program with gpu uses 13 seconds. I would like to ask if there is any way to improve efficiency?
